# Generated by Django 4.0.4 on 2022-05-21 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('ID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Grade', models.IntegerField(null=True)),
                ('Quantity', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MinAge', models.IntegerField(blank=True, null=True)),
                ('MaxAge', models.IntegerField(blank=True, null=True)),
                ('MaxQuantity', models.IntegerField(blank=True, default=45, null=True)),
                ('ClassNumber', models.IntegerField(blank=True, default=45, null=True)),
                ('SubjectNumber', models.IntegerField(blank=True, default=45, null=True)),
                ('PassMark', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('ID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=50, null=True)),
                ('LastName', models.CharField(max_length=10, null=True)),
                ('Birthday', models.DateTimeField(blank=True, null=True)),
                ('Email', models.CharField(blank=True, max_length=100, null=True)),
                ('Gender', models.CharField(max_length=10, null=True)),
                ('Address', models.CharField(blank=True, max_length=10, null=True)),
                ('Classname', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.class')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('ID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('ID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=50, null=True)),
                ('LastName', models.CharField(max_length=10, null=True)),
                ('Birthday', models.DateTimeField(blank=True, null=True)),
                ('Email', models.CharField(blank=True, max_length=100, null=True)),
                ('Gender', models.CharField(max_length=10, null=True)),
                ('Address', models.CharField(blank=True, max_length=10, null=True)),
                ('SubjectID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Student_Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudentID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.student')),
                ('TeacherID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=10, null=True)),
                ('Mark', models.FloatField(null=True)),
                ('StudentID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.student')),
                ('SubjectID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Class_Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Classname', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.class')),
                ('TeacherID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.teacher')),
            ],
        ),
    ]
