# Generated by Django 4.0.4 on 2022-06-05 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_remove_student_teacher_studentid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semeter',
            fields=[
                ('semeter', models.IntegerField(max_length=1, primary_key=True, serialize=False)),
            ],
        ),
    ]
