# Generated by Django 4.0.4 on 2022-06-05 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_semeter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semeter',
            name='semeter',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
