# Generated by Django 4.0.4 on 2022-06-05 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_alter_year_school_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='semeter',
            name='year_school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.year'),
        ),
    ]
