# Generated by Django 4.0.4 on 2022-05-27 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_alter_teacher_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='Grade',
        ),
        migrations.AddField(
            model_name='class',
            name='ClassName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='Quantity',
            field=models.IntegerField(blank=True, default=33, null=True),
        ),
    ]
