# Generated by Django 4.0.4 on 2022-05-28 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_remove_class_grade_class_classname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='HeadTeacher',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='More',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
