# Generated by Django 4.0.4 on 2022-05-28 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_class_headteacher_class_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='ClassName',
        ),
        migrations.AlterField(
            model_name='class',
            name='More',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
