# Generated by Django 4.0.4 on 2022-06-05 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_alter_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='ID',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
