# Generated by Django 4.0.4 on 2022-06-05 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_alter_student_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report_Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.FloatField(null=True)),
                ('Classname', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.class')),
                ('StudentID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.student')),
            ],
        ),
    ]
