# Generated by Django 4.0.4 on 2022-05-28 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_remove_class_classname_alter_class_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='HeadTeacher',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.teacher'),
        ),
    ]
