# Generated by Django 4.0.3 on 2022-05-29 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_alter_class_headteacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
