# Generated by Django 4.0.4 on 2022-06-05 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_report_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mark',
            name='semester',
        ),
        migrations.DeleteModel(
            name='Semeter',
        ),
    ]
