# Generated by Django 4.0.4 on 2022-06-05 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_remove_mark_semester_delete_semeter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semeter',
            fields=[
                ('semeter', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='mark',
            name='semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.semeter'),
        ),
    ]
