# Generated by Django 4.0.3 on 2022-05-31 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_alter_student_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Year',
            fields=[
                ('year_school', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
    ]
