# Generated by Django 4.0.4 on 2022-06-05 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_semeter_mark_semester'),
    ]

    operations = [
        migrations.RenameField(
            model_name='semeter',
            old_name='semeter',
            new_name='semeter_id',
        ),
    ]
