# Generated by Django 4.0.4 on 2022-06-05 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_rename_semeter_semeter_semeter_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='report_class',
            name='semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.semeter'),
        ),
    ]
