# Generated by Django 4.0.3 on 2022-05-31 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0014_alter_mark_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mark',
            name='Type',
        ),
    ]
