# Generated by Django 4.0.4 on 2022-06-05 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0014_report_class_semester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report_class',
            name='Classname',
        ),
        migrations.AddField(
            model_name='report_class',
            name='year_school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.year'),
        ),
    ]
