# Generated by Django 4.0.4 on 2022-06-01 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0015_remove_mark_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='year',
            old_name='year_school',
            new_name='school_year',
        ),
    ]
