# Generated by Django 4.0.4 on 2022-06-07 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0015_remove_report_class_classname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mark',
            old_name='Mark',
            new_name='Mark15',
        ),
        migrations.AddField(
            model_name='mark',
            name='Mark60',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='mark',
            name='MarkFinal',
            field=models.FloatField(null=True),
        ),
    ]
