# Generated by Django 4.0.4 on 2022-06-01 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0016_rename_year_school_year_school_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='year_school',
            new_name='school_year',
        ),
    ]
