# Generated by Django 4.0.4 on 2022-06-07 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0016_rename_mark_mark_mark15_mark_mark60_mark_markfinal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='Mark15',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='mark',
            name='Mark60',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='mark',
            name='MarkFinal',
            field=models.FloatField(default=0, null=True),
        ),
    ]
