# Generated by Django 4.0.4 on 2022-06-15 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0017_alter_mark_mark15_alter_mark_mark60_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='Quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
